steps:
  # Paso 1: Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/gcr-repo/fastapi-swe', '.']

  # Paso 2: Ejecutar pruebas
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--rm', 'us-central1-docker.pkg.dev/$PROJECT_ID/gcr-repo/fastapi-swe', 'pytest', 'tests']
  
  # Paso 3: Subir la imagen al Container Registry (si las pruebas pasan)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/gcr-repo/fastapi-swe']

  # Paso 4: Desplegar la imagen en Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'fastapi-swe'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/gcr-repo/fastapi-swe'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'


# Definimos el bucket para almacenar los logs y la cuenta de servicio
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/cloudbuild-deploy@latam-desafio.iam.gserviceaccount.com'
logsBucket: 'gs://fastapi-swe-cloudbuild'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/gcr-repo/fastapi-swe'
